# Generated by Django 5.1.6 on 2025-02-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("payment", "Payment"), ("fine", "Fine")],
                default="payment",
                max_length=10,
            ),
        ),
    ]
