# Generated by Django 5.1.6 on 2025-03-02 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_service", "0002_payment_status_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
