# Generated by Django 5.1.6 on 2025-03-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment_service", "0003_payment_session_expires_at_alter_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-session_expires_at"]},
        ),
    ]
