# Generated by Django 5.1.6 on 2025-03-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing_service", "0005_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["-borrow_date"]},
        ),
    ]
